# Form implementation generated from reading ui file 'previewui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PreviewDialog(object):
    def setupUi(self, PreviewDialog):
        PreviewDialog.setObjectName("PreviewDialog")
        PreviewDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        PreviewDialog.resize(402, 428)
        PreviewDialog.setMinimumSize(QtCore.QSize(10, 10))
        PreviewDialog.setAutoFillBackground(True)
        PreviewDialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        PreviewDialog.setSizeGripEnabled(True)
        PreviewDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreviewDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imagePreviewLabel = QtWidgets.QLabel(parent=PreviewDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagePreviewLabel.sizePolicy().hasHeightForWidth())
        self.imagePreviewLabel.setSizePolicy(sizePolicy)
        self.imagePreviewLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.imagePreviewLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.imagePreviewLabel.setLineWidth(0)
        self.imagePreviewLabel.setText("")
        self.imagePreviewLabel.setObjectName("imagePreviewLabel")
        self.verticalLayout.addWidget(self.imagePreviewLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 15, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aspectratioCheckBox = QtWidgets.QCheckBox(parent=PreviewDialog)
        self.aspectratioCheckBox.setChecked(True)
        self.aspectratioCheckBox.setObjectName("aspectratioCheckBox")
        self.horizontalLayout.addWidget(self.aspectratioCheckBox, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.doneButton = QtWidgets.QPushButton(parent=PreviewDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneButton.sizePolicy().hasHeightForWidth())
        self.doneButton.setSizePolicy(sizePolicy)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout.addWidget(self.doneButton, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PreviewDialog)
        QtCore.QMetaObject.connectSlotsByName(PreviewDialog)

    def retranslateUi(self, PreviewDialog):
        _translate = QtCore.QCoreApplication.translate
        PreviewDialog.setWindowTitle(_translate("PreviewDialog", "Preview"))
        self.aspectratioCheckBox.setText(_translate("PreviewDialog", "AR"))
        self.doneButton.setText(_translate("PreviewDialog", "Done"))
