# Form implementation generated from reading ui file 'colorsui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ColorsUI(object):
    def setupUi(self, ColorsUI):
        ColorsUI.setObjectName("ColorsUI")
        ColorsUI.resize(200, 350)
        ColorsUI.setMinimumSize(QtCore.QSize(200, 350))
        ColorsUI.setMaximumSize(QtCore.QSize(200, 350))
        self.colors_ListWidget = QtWidgets.QListWidget(parent=ColorsUI)
        self.colors_ListWidget.setGeometry(QtCore.QRect(10, 40, 181, 301))
        self.colors_ListWidget.setObjectName("colors_ListWidget")
        self.label = QtWidgets.QLabel(parent=ColorsUI)
        self.label.setGeometry(QtCore.QRect(16, 12, 141, 21))
        self.label.setObjectName("label")

        self.retranslateUi(ColorsUI)
        QtCore.QMetaObject.connectSlotsByName(ColorsUI)

    def retranslateUi(self, ColorsUI):
        _translate = QtCore.QCoreApplication.translate
        ColorsUI.setWindowTitle(_translate("ColorsUI", "Dialog"))
        self.label.setText(_translate("ColorsUI", "Available colors:"))
